const eventSeed = [
  {
    name : "alt-J",
    genre : "Concerts",
    description : "Alt-J will be performing their fall headling tour live at the Duke Energy Center's Memorial Auditorium on Nov. 3.",
    link : "http://www.dukeenergycenterraleigh.com/event/alt-j-private-event-8559",
    date : Date("2017-011-03T00:00:00.000Z"),
    startTime : "20:00",
    endTime : "23:00",
    allDay : false,
    location : "Memorial Auditorium at Duke Energy Center for the Performing Arts",
    address : "2 E. South St.",
    city : "Raleigh",
    zipCode : "27601",
    kidFriendly : false,
    petFriendly : false,
    advert : false,
    vote : {
        negative : [],
        positive : []
    },
    attendingList : [],
    state : "NC",
    __v : 0
},
{
  name : "General Hugh Shelton Leadership Forum",
  genre : "Social",
  description : "Now in its 16th year, this annual seminar series focuses on leadership development and its importance, working closely with Research Triangle Park based industries, local businesses and executives and students from area colleges and universities.",
  link : "https://sheltonleadership.ncsu.edu/",
  date : Date("2017-011-03T00:00:00.000Z"),
  startTime : "07:45",
  endTime : "14:00",
  allDay : false,
  location : "McKimmon Conference & Training Center",
  address : "1101 Gorman St.",
  city : "Raleigh",
  zipCode : "27606",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "NC State Homecoming Parade",
  genre : "Outdoors",
  description : "NC State's Red and White Week will be capped off by the annual Homecoming Parade.",
  link : "https://redwhiteweek.ncsu.edu/event/red-and-white-week-parade/",
  date : Date("2017-011-03T00:00:00.000Z"),
  startTime : "16:00",
  endTime : "19:00",
  allDay : false,
  location : "Hillsborough Street Community Service Corporation",
  address : "2416 Hillsborough St.",
  city : "Raleigh",
  zipCode : "27607",
  kidFriendly : true,
  petFriendly : true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Full Moon Paddle",
  genre : "Outdoors",
  description : "Experience the beauty and tranquility of Lake Benson at night. Participants will paddle in a canoe or solo kayak at their leisure, have access to a telescope to view the moon and enjoy s'mores.",
  link : "http://www.garnernc.gov/Home/Components/Calendar/Event/905/19?curm=11&cury=2017",
  date : Date("2017-011-04T00:00:00.000Z"),
  startTime : "18:00",
  endTime : "20:00",
  allDay : false,
  location : "Lake Benson Park",
  address : "921 Buffaloe Rd.",
  city : "Garner",
  zipCode : "27529",
  kidFriendly : true,
  petFriendly : true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Holly Springs Winter Farmers Market Outdoor",
  genre : "Outdoors",
  description : "From November through April, the Holly Springs Farmers Market will be open the first Saturday of each month outdoors in the E. Center Street parking lot weather permitting. On the third Saturday of each month, the market will be indoors at the Cultural Center. The market will even have a few vendors who will be offering greenhouse-grown produce throughout the season!",
  link : "http://www.hollyspringsnc.us/farmersmarket/",
  date : Date("2017-011-04T00:00:00.000Z"),
  startTime : "09:30",
  endTime : "12:00",
  allDay : false,
  location : "Holly Springs Farmers Market",
  address : "128 S. Main St.",
  city : "Holly Springs",
  zipCode : "27540",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Big Daddy Love",
  genre : "Concerts",
  description : "Big Daddy Love will be performing live with The Company Stores at The Pour House Music Hall",
  link : "http://thepourhousemusichall.com/event/big-daddy-love/",
  date : Date("2017-011-03T00:00:00.000Z"),
  startTime : "21:00",
  endTime : "23:00",
  allDay : false,
  location : "The Pour House Music Hall",
  address : "224 S. Blount St.",
  city : "Raleigh",
  zipCode : "27601",
  kidFriendly : false,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Colin Joseph Neal",
  genre : "Concerts",
  description : "Colin Joseph Neal will be performing live at Abbey Road in Apex.",
  link : "http://abbeyroadnc.com/apex-events/",
  date : Date("2017-011-03T00:00:00.000Z"),
  startTime : "20:00",
  endTime : "23:00",
  allDay : false,
  location : "Abbey Road Tavern & Grill - Apex",
  address : "1700 Center St.",
  city : "Apex",
  zipCode : "27502",
  kidFriendly : false,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Beam Brothers",
  genre : "Concerts",
  description : "Country and gospel group Beam Brothers will be performing live at Lorraine's Coffee House.",
  link : "http://lorrainescoffeehouse.com/events/",
  date : Date("2017-011-04T00:00:00.000Z"),
  startTime : "19:30",
  endTime : "21:30",
  allDay : false,
  location : "Lorraine's Coffee House",
  address : "101 Timber Pointe Ln.",
  city : "Garner",
  zipCode : "27529",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Ewe's Tree",
  genre : "Concerts",
  description : "Ewe's Tree will be performing live Irish music at Doherty's in Cary.",
  link : "http://www.visitraleigh.com/includes/calendar-of-events/Ewe-s-Tree/54014/",
  date : Date("2017-011-08T00:00:00.000Z"),
  startTime : "18:00",
  endTime : "21:00",
  allDay : false,
  location : "Doherty's Irish Pub & Restaurant - Cary",
  address : "1979 High House Rd.",
  city : "Cary",
  zipCode : "27519",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
}
]

module.exports = eventSeed;
