const eventSeed = [
  {
    name : "alt-J",
    genre : "Concerts",
    description : "Alt-J will be performing their fall headling tour live at the Duke Energy Center's Memorial Auditorium on Nov. 3.",
    link : "http://www.dukeenergycenterraleigh.com/event/alt-j-private-event-8559",
    date : new Date("2017-011-03"),
    startTime : "20:00",
    endTime : "23:00",
    allDay : false,
    location : "Memorial Auditorium at Duke Energy Center for the Performing Arts",
    address : "2 E. South St.",
    city : "Raleigh",
    zipCode : "27601",
    kidFriendly : false,
    petFriendly : false,
    advert : false,
    vote : {
        negative : [],
        positive : []
    },
    attendingList : [],
    state : "NC",
    __v : 0
},
{
  name : "General Hugh Shelton Leadership Forum",
  genre : "Social",
  description : "Now in its 16th year, this annual seminar series focuses on leadership development and its importance, working closely with Research Triangle Park based industries, local businesses and executives and students from area colleges and universities.",
  link : "https://sheltonleadership.ncsu.edu/",
  date : new Date("2017-011-03"),
  startTime : "07:45",
  endTime : "14:00",
  allDay : false,
  location : "McKimmon Conference & Training Center",
  address : "1101 Gorman St.",
  city : "Raleigh",
  zipCode : "27606",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "NC State Homecoming Parade",
  genre : "Outdoors",
  description : "NC State's Red and White Week will be capped off by the annual Homecoming Parade.",
  link : "https://redwhiteweek.ncsu.edu/event/red-and-white-week-parade/",
  date : new Date("2017-011-03"),
  startTime : "16:00",
  endTime : "19:00",
  allDay : false,
  location : "Hillsborough Street Community Service Corporation",
  address : "2416 Hillsborough St.",
  city : "Raleigh",
  zipCode : "27607",
  kidFriendly : true,
  petFriendly : true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Full Moon Paddle",
  genre : "Outdoors",
  description : "Experience the beauty and tranquility of Lake Benson at night. Participants will paddle in a canoe or solo kayak at their leisure, have access to a telescope to view the moon and enjoy s'mores.",
  link : "http://www.garnernc.gov/Home/Components/Calendar/Event/905/19?curm=11&cury=2017",
  date : new Date("2017-011-04"),
  startTime : "18:00",
  endTime : "20:00",
  allDay : false,
  location : "Lake Benson Park",
  address : "921 Buffaloe Rd.",
  city : "Garner",
  zipCode : "27529",
  kidFriendly : true,
  petFriendly : true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Holly Springs Winter Farmers Market Outdoor",
  genre : "Outdoors",
  description : "From November through April, the Holly Springs Farmers Market will be open the first Saturday of each month outdoors in the E. Center Street parking lot weather permitting. On the third Saturday of each month, the market will be indoors at the Cultural Center. The market will even have a few vendors who will be offering greenhouse-grown produce throughout the season!",
  link : "http://www.hollyspringsnc.us/farmersmarket/",
  date : new Date("2017-011-04"),
  startTime : "09:30",
  endTime : "12:00",
  allDay : false,
  location : "Holly Springs Farmers Market",
  address : "128 S. Main St.",
  city : "Holly Springs",
  zipCode : "27540",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Big Daddy Love",
  genre : "Concerts",
  description : "Big Daddy Love will be performing live with The Company Stores at The Pour House Music Hall",
  link : "http://thepourhousemusichall.com/event/big-daddy-love/",
  date : new Date("2017-011-03"),
  startTime : "21:00",
  endTime : "23:00",
  allDay : false,
  location : "The Pour House Music Hall",
  address : "224 S. Blount St.",
  city : "Raleigh",
  zipCode : "27601",
  kidFriendly : false,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Colin Joseph Neal",
  genre : "Concerts",
  description : "Colin Joseph Neal will be performing live at Abbey Road in Apex.",
  link : "http://abbeyroadnc.com/apex-events/",
  date : new Date("2017-011-03"),
  startTime : "20:00",
  endTime : "23:00",
  allDay : false,
  location : "Abbey Road Tavern & Grill - Apex",
  address : "1700 Center St.",
  city : "Apex",
  zipCode : "27502",
  kidFriendly : false,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Beam Brothers",
  genre : "Concerts",
  description : "Country and gospel group Beam Brothers will be performing live at Lorraine's Coffee House.",
  link : "http://lorrainescoffeehouse.com/events/",
  date : new Date("2017-011-04"),
  startTime : "19:30",
  endTime : "21:30",
  allDay : false,
  location : "Lorraine's Coffee House",
  address : "101 Timber Pointe Ln.",
  city : "Garner",
  zipCode : "27529",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Ewe's Tree",
  genre : "Concerts",
  description : "Ewe's Tree will be performing live Irish music at Doherty's in Cary.",
  link : "http://www.visitraleigh.com/includes/calendar-of-events/Ewe-s-Tree/54014/",
  date : new Date("2017-011-08"),
  startTime : "18:00",
  endTime : "21:00",
  allDay : false,
  location : "Doherty's Irish Pub & Restaurant - Cary",
  address : "1979 High House Rd.",
  city : "Cary",
  zipCode : "27519",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "NC State Volleyball vs. Syracuse",
  genre : "Sports",
  description : "The NC State Women's Volleyball Team will host Syracuse at Reynolds Coliseum. Stay after the match to get a 2017 Volleyball poster signed by your favorite players.",
  link : "http://gopack.com/index.aspx?path=wvball",
  date : new Date("2017-011-03"),
  startTime : "19:00",
  endTime : "21:00",
  allDay : false,
  location : "Reynolds Coliseum (North Carolina State University)",
  address : "2411 Dunn Ave.",
  city : "Raleigh",
  zipCode : "27695",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "NHL Carolina Hurricanes vs. Florida Panthers",
  genre : "Sports",
  description : "The Carolina Hurricanes take on the Florida Panthers at PNC Arena.",
  link : "http://hurricanes.nhl.com/club/schedule.htm",
  date : new Date("2017-011-07"),
  startTime : "19:00",
  endTime : "21:00",
  allDay : false,
  location : "PNC Arena",
  address : "1400 Edwards Mill Rd.",
  city : "Raleigh",
  zipCode : "27607",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "NC State Women's Basketball vs. Jacksonville",
  genre : "Sports",
  description : "The North Carolina State Women's Basketball Team will host Jacksonville at Reynolds Coliseum.",
  link : "http://gopack.com/schedule.aspx?path=wbball",
  date : new Date("2017-011-10"),
  startTime : "17:00",
  endTime : "20:00",
  allDay : false,
  location : "Reynolds Coliseum (North Carolina State University)",
  address : "2411 Dunn Ave.",
  city : "Raleigh",
  zipCode : "27695",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Carrboro Cheer - Townsend Bertram Tree Lighting",
  genre : "Social",
  description : "Kick off the holiday season with the lighting of the tree a Carr Mill Mall including a free outdoor concert by Ella Bertram.",
  link : "https://tbandc.com/calendar/2017/11/3/tree-lighting",
  date : new Date("2017-011-03"),
  startTime : "18:00",
  endTime : "21:00",
  allDay : false,
  location : "Carr Mill Mall",
  address : "200 North Greensboro St",
  city : "Carrboro",
  zipCode : "27510",
  kidFriendly : true,
  petFriendly : true,
  advert : true,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Toddler Preschool Playtime",
  genre : "Social",
  description : "Parents and young children (5 & under) can come enjoy some unstructured playtime in the spacious Century Hall. There will be music to dance to, blocks, crawl tunnels, and other toys to play with and plenty of space. It will be a great opportunity to meet new friends and playmates. No registration required. Ages: 1-5",
  link : "http://www.carrbororec.org/275/Recreation-Parks",
  date : new Date("2017-011-07"),
  startTime : "10:00",
  endTime : "12:00",
  allDay : false,
  location : "Carrboro Century Center - Century Hall",
  address : "100 N. Greensboro St.",
  city : "Carrboro",
  zipCode : "27510",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "12th Annual Carrboro Film Festival",
  genre : "Arts",
  description : "The Carrboro Film Festival is a celebration of the film and video creativity we have right here in NC. All filmmakers, from beginner to well established professional, are welcome to submit a production. For more information and full schedule of events please visit: http://www.CarrboroFilmFestival.com",
  link : "http://www.carrborofilmfestival.com/",
  date : new Date("2017-011-18"),
  startTime : "08:00",
  endTime : "",
  allDay : true,
  location : "The Arts Center",
  address : "300-G E. Main St.",
  city : "Carrboro",
  zipCode : "27510",
  kidFriendly : true,
  petFriendly : false,
  advert : true,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "12th Annual Carrboro Film Festival",
  genre : "Arts",
  description : "The Carrboro Film Festival is a celebration of the film and video creativity we have right here in NC. All filmmakers, from beginner to well established professional, are welcome to submit a production. For more information and full schedule of events please visit: http://www.CarrboroFilmFestival.com",
  link : "http://www.carrborofilmfestival.com/",
  date : new Date("2017-011-19"),
  startTime : "08:00",
  endTime : "",
  allDay : true,
  location : "The Arts Center",
  address : "300-G E. Main St.",
  city : "Carrboro",
  zipCode : "27510",
  kidFriendly : true,
  petFriendly : false,
  advert : true,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Rodeo on Rosemary",
  genre : "Community",
  description : "This lively street celebration will again be on East Rosemary Street between Henderson and North Columbia Streets. Bring the kids and enjoy the afternoon with giant games, a miniature golf course on The Plaza and a live DJ spinning your favorite tunes.",
  link : "http://www.downtownchapelhill.com/calendar/2017/11/5/rodeo-on-rosemary",
  date : new Date("2017-011-05"),
  startTime : "12:00",
  endTime : "16:00",
  allDay : false,
  location : "Rosemary St.",
  address : "Rosemary St.",
  city : "Chapel Hill",
  zipCode : "27516",
  kidFriendly : true,
  petFriendly : false,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "76th Annual N.C. Gourd Arts and Crafts Festival",
  genre : "Festival",
  description : "This festival features displays of gourds from around the world, special gourd workshops and vendors of dried gourds, gourd seeds, gourd crafts, gourd art, books, t-shirts and crafting supplies.",
  link : "http://www.ncgourdsociety.org/festival",
  date : new Date("2017-011-04"),
  startTime : "09:00",
  endTime : "17:00",
  allDay : false,
  location : "Holshouser Building at North Carolina State Fairgrounds",
  address : "1025 Blue Ridge Rd.",
  city : "Raleigh",
  zipCode : "27607",
  kidFriendly : true,
  petFriendly : false,
  control: true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Moonlight in the Garden 2017",
  genre : "Festival",
  description : "Moonlight in the Garden is making an exciting return at the JC Raulston Arboretum! For the second time in over a decade, the JCRA will open its doors for this outstanding nighttime event. Follow the beautiful lighted paths through the garden and prepare to be amazed by the delicious food truck eats, soulful live music, warm fires, hot cider, and, of course, Raleigh's lively community!",
  link : "https://jcra.ncsu.edu/events/details.php?ID=1498",
  date : new Date("2017-011-09"),
  startTime : "18:00",
  endTime : "21:00",
  allDay : false,
  location : "JC Raulston Arboretum at North Carolina State University",
  address : "4415 Beryl Rd.",
  city : "Raleigh",
  zipCode : "27606",
  kidFriendly : true,
  petFriendly : false,
  control: true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
},
{
  name : "Vintage Fan Fair",
  genre : "Festival",
  description : "Join Vintage Lifestyle Experience in Celebrating Nostalgia™ Veterans Day Weekend! Be fully immersed in a nostalgic experience with a marketplace of vendors, retro activities, presentations, an author-signing event, pop-up entertainment and a special tribute to our vets. Be sure to check out the Glamper Showcase - the first one of it's kind in Raleigh! Tour 20+ vintage campers all decked out to the nines!",
  link : "http://www.vintagefanfair.com/",
  date : new Date("2017-011-10"),
  startTime : "12:00",
  endTime : "20:00",
  allDay : false,
  location : "Holshouser Building at North Carolina State Fairgrounds",
  address : "1025 Blue Ridge Rd.",
  city : "Raleigh",
  zipCode : "27607",
  kidFriendly : true,
  petFriendly : false,
  control: true,
  advert : false,
  vote : {
      negative : [],
      positive : []
  },
  attendingList : [],
  state : "NC",
  __v : 0
}
]

module.exports = eventSeed;
